blog/urls.py
from django.urls import path

from . import  views
app_name = "blog"
urlpatterns = [
    path('', views.index, name="home"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.loginView, name="login"),
    path('logout/', views.LogoutView, name="logout"),
    path('profile/<str:pk>/',views.dashboard,name="profile"),
    path('add_post/',views.Addpost,name="add_post"),
    path('edit_post/<pk>/',views.updatePost,name="edit_post"),
    path('delete_post/<pk>/',views.deletePost,name="delete_post"),
    path('postdetail/<int:pk>/',views.detailPost,name='postdetail'),
    path('categorypost/<str:pk>/lists/',views.category_post_list,name="category_posts"),
    path('likepost/<int:pk>/',views.likeview,name="like_post"),
    path('changeprofilepic/',views.changeProfilePic,name="changepropic"),
    path('changecoverpic/',views.changeCoverPic,name="changecoverpic"),

    # path('add_post/<str:pk>/',views.Addpost,name="add_post"),
]

mini_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=128)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # description = models.TextField()
    description = RichTextField(blank=True, null=True)
    creation_date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=128, default="coding")
    image = models.ImageField(upload_to='images/post/', blank=True, null=True)
    like = models.ManyToManyField(User, related_name="Post")

    def totalLike(self):
        return self.like.count()

    def __str__(self):
        return '{} of {}'.format(self.title, self.id)


class SecondarySchool(models.Model):
    name = models.CharField(max_length=200)
    join_date = models.DateField()
    end_date = models.DateField()
    completed = models.BooleanField(default=False)


class HigherSecondarySchool(models.Model):
    name = models.CharField(max_length=200)
    join_date = models.DateField()
    end_date = models.DateField()
    completed = models.BooleanField(default=False)


class College(models.Model):
    name = models.CharField(max_length=200)
    course = models.CharField(max_length=200)
    join_date = models.DateField()
    end_date = models.DateField()
    completed = models.BooleanField(default=False)


class UserProfile(models.Model):
    profile_Image = models.ImageField(default="images/default_profile/default-profile.jpg",
                                      upload_to='images/profile_pic/')
    bio = models.TextField(null=True)
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    cover_Image = models.ImageField(upload_to='images/cover_img/', null=True, blank=True)
    secondary_school = models.ForeignKey(SecondarySchool, null=True, blank=True, on_delete=models.DO_NOTHING)
    higher_secondary_school = models.ForeignKey(HigherSecondarySchool, null=True, blank=True,
                                                on_delete=models.DO_NOTHING)

    def __str__(self):
        return "{}".format(self.user)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=128)
    description = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} of {}".format(self.post.title, self.name)

    def total_comment(self):
        return Comment.objects.all().count()

# class Like(models.Model):
#     like_post = models.ForeignKey(Post,on_delete=models.CASCADE)
#     like_by = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
#
#     def __str__(self):
#         return str(self.pk)

blog/forms.py
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile,Post,Category,Comment
from ckeditor.fields import CKEditorWidget

choices = Category.objects.all().values_list('name','name')
choice_list = []
for item in choices:
    choice_list.append(item)

class SignUp(UserCreationForm):
    username = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label="Password (again)", widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username','password1','password2']

    def save(self, commit=True):
        user = super(SignUp, self).save(commit=False)
        first_name = user.username.split('@')
        user.first_name = first_name[0]
        user.email = user.username
        user.save()
        return user

class Login(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username','password']

class PostForm(forms.ModelForm):
    category = forms.ModelChoiceField(Category.objects.order_by('name'),
                                      widget=forms.Select(attrs={'class':'form-control'}),
                                      required=True,empty_label="Select Category Options")
    description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Post
        fields = ['title','category','description','image']
        widgets = {'title':forms.TextInput(attrs={'class':'form-control','placeholder':"whats in your mind"}),

                   'image':forms.FileInput(attrs={'class':'form-control-file'}),
                   }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=['description']
        widgets = {'description':forms.TextInput(attrs={'class':'form-control',
                                                        'placeholder':'Comment your thoughts'})}
class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_Image','cover_Image','bio']

class ChangeProfilePicForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_Image']

blog/views.py
from django.shortcuts import render
from django.contrib.auth.models import User,Group
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from .forms import SignUp,Login,ProfileForm,PostForm,ChangeProfilePicForm,CommentForm
from .models import Post,UserProfile,Comment
# Create your views here.


def index(request):
    posts = Post.objects.all()

    allpost = posts
    allposts = []
    liked = []
     # likes = Like.objects.filter(like_by__user=request.user)
    for i in posts:
        if i.like.filter(id=request.user.id).exists():
            liked.append(True)
        else:
            liked.append(False)
    print("checking liked or not",liked)
    # print(likes)
    for categories in allpost:
        if categories.category not in allposts:
            allposts.append(categories.category)


    comment = Comment.objects.all().order_by('-id')[:4]
    context = {'posts': posts,
               'allposts': allposts,
               'liked': liked,
               'comments':comment,
               }

    return render(request, 'blog/home.html',context)


def category_post_list(request,pk):
    posts = Post.objects.filter(category=pk).order_by('-creation_date')
    allpost = Post.objects.all()
    allposts = []

    for categories in allpost:
        # print("check", categories.category)
        if categories.category not in allposts:
            allposts.append(categories.category)
    print("catogories:",allposts)

    return render(request,'blog/category.html',{'posts':posts,'allposts':allposts})


def detailPost(request,pk):
    post = Post.objects.get(id=pk)
    if request.method == "POST":
        if request.user.is_authenticated:
            commentform = CommentForm(request.POST)
            if commentform.is_valid():
                comment = commentform.cleaned_data['description']
                user= request.user.username
                cm = Comment.objects.create(post=post,name=user,description=comment)
                cm.save()
                return HttpResponseRedirect('/postdetail/'+str(pk)+'/')
        else:
            return HttpResponseRedirect('/login/')
    else:
        commentform = CommentForm()

    return render(request,'blog/postdetail.html',{'post':post,'commentform':commentform})


def signup(request):
    if request.method == "POST":
        form = SignUp(request.POST)
        if form.is_valid():
            usersave = form.save()
            groups = Group.objects.get(name='Users')
            usersave.groups.add(groups)
            UserProfile.objects.create(user=usersave)

            return HttpResponseRedirect('/login/')

    else:
        form = SignUp(label_suffix=" ", auto_id=True)

    return render(request, 'blog/signup.html', {'form':form})


def loginView(request):
    if not request.user.is_authenticated:
        if request.method == "POST":
            loginform = Login(request=request, data=request.POST)
            if loginform.is_valid():
                uname = loginform.cleaned_data['username']
                password = loginform.cleaned_data['password']
                validauth = authenticate(username=uname,password=password) # it returns none if user not found
                if validauth is not None:
                    login(request,validauth)
                    return HttpResponseRedirect('/')
            else:
                messages.error(request,'Invalid Id or Password')
        else:
            loginform = Login()

        return render(request,'blog/login.html',{'loginform':loginform})
    else:
        return HttpResponseRedirect('/')


def LogoutView(request):
    logout(request)
    return HttpResponseRedirect('/')


def Addpost(reqeust):
    if reqeust.user.is_authenticated:
        if reqeust.method == "POST":
            pf = PostForm(reqeust.POST,reqeust.FILES)
            if pf.is_valid():
                title = pf.cleaned_data['title']
                description = pf.cleaned_data['description']
                category = pf.cleaned_data['category']
                user = reqeust.user
                image = pf.cleaned_data['image']
                postdata = Post(title=title, description=description, user=user,category=category,image=image)
                postdata.save()
                return HttpResponseRedirect('/')

        else:
            pf = PostForm()
    else:
        return HttpResponseRedirect('/login/')
    return render(reqeust,'blog/add_post.html',{'postform':pf})

def updatePost(request,pk):
    if request.user.is_authenticated:
        getpost = Post.objects.get(pk=pk, user__username=request.user.username)
        if request.method == "POST":
            postupdateform = PostForm(request.POST, initial={
                "title": getpost.title,
                "description": getpost.description,
                "image": getpost.image,
                "category":getpost.category,
            },instance=getpost)
            if postupdateform.is_valid():
                postupdateform.save()
                return HttpResponseRedirect('/profile/'+request.user.username+'/')
        if request.method == "GET":
            postupdateform = PostForm(initial={
                "title":getpost.title,
                "description":getpost.description,
                "image":getpost.image,
                "category":getpost.category,
            })
            postid = getpost.id
            return render(request,'blog/add_post.html',context={'postupdateform':postupdateform,'postid':postid})
    else:
        return HttpResponseRedirect('/login/')

def deletePost(request,pk):
    if request.user.is_authenticated:
        post = Post.objects.get(user__username=request.user, pk=pk)
        if request.method == "POST":
            if post:
                post.delete()
                return HttpResponseRedirect('/profile/'+request.user.username+'/')
        if request.method == "GET":
            post_title = post.title
    else:
        return HttpResponseRedirect('/login/')
    return render(request,'blog/profile.html',{"post_title":post_title})


def likeview(request,pk):
    if request.user.is_authenticated:
        if request.method == "POST":
            post = Post.objects.get(id=pk)
            if post.like.filter(id=request.user.id).exists():
                post.like.remove(request.user)
            else:
                post.like.add(request.user)
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/login/')


@login_required(login_url="/login/")
def dashboard(request,pk):
    dash = ProfileForm()
    chpic = ChangeProfilePicForm()
    print(pk)
    userprofile = UserProfile.objects.get(user__username=pk)
    post_data = Post.objects.filter(user__username=pk)
    context = {"posts":post_data,'dashboard':dash, 'userprofile':userprofile, 'chpic':chpic}
    return render(request,'blog/profile.html',context)


@login_required(login_url="/login/")
def changeProfilePic(request):
    if request.method == 'POST':
        print(request.FILES)

        #  client file saved / update without using any form

        # here i used DropZone js

        profilepic = request.FILES['file']
        save_pic = UserProfile.objects.get(user=request.user)
        save_pic.profile_Image = profilepic
        save_pic.save()
        # return HttpResponseRedirect('/profile/'+str(save_pic.user)+"/")

    return render(request,'blog/profile.html')


@login_required(login_url="/login/")
def changeCoverPic(request):
    if request.method == "POST":
        cover_pic = request.FILES['file']
        save_pic = UserProfile.objects.get(user=request.user)
        save_pic.cover_Image = cover_pic
        save_pic.save()


    return render(request,'blog/profile.html')

blog/templates/blog/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

blog/templates/blog/add_post.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}
{% block content %}
    {% include 'blog/navbar.html' %}
<div class="row container">
<div class="col-md-6 offset-4">
    <form action="{% if not postupdateform %}{% url 'blog:add_post' %}{% else %}{% url 'blog:edit_post' postid %}{% endif %}" method="POST" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {% if postupdateform %}
            {{postupdateform.media}}
            {% for i in postupdateform %}
                <div class="mb-4">
                    <label for="{{i.auto_id}}" class="control-label text-muted">{{i.label}}</label>
                    {{i}}
                </div>
            {% endfor %}
        {% else %}
        {{postform.media}}
            {% for i in postform %}
                <div class="mb-4">
                    <label for="{{i.auto_id}}" class="control-label text-muted">{{i.label}}</label>
                    {{i}}
                </div>

            {% endfor %}
        {% endif %}
        <div class="mb-4">
            <input type="submit" class="btn btn-warning" value="{% if not postupdateform %}Add {% else %}Edit{% endif %}">
            <a class="btn btn-danger" href="{% url 'blog:profile' request.user.username %}">Cancel</a>
        </div>
    </form>
</div>
</div>
{% endblock %}

blog/templates/blog/category.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}
{% block content %}
{% include 'blog/navbar.html' %}
    <section class="mt-4 content">
    <div class="container">
        {% for cats in posts %}
            {% if forloop.first %}
                <p class="h4 offset-2">Filtered - {{cats.category}}</p>
            {% endif %}
        {% endfor %}
        <div class="row">

            <div class="col-md-6 offset-1 posts">
                {% if posts %}
                    {% for post in posts %}
                    <div class="card mb-5" style="width: 40rem;">
                        <a href="{% url 'blog:profile' post.user %}" class="nav-link alert text-dark mb-0">
                            {% if post.user.userprofile.profile_Image %}
                            <img src="/media/{{post.user.userprofile.profile_Image}}" id="profilepic" alt="dp" class="mr-3">
                            {% endif %}
                            {% if post.user.first_name %}
                                {{post.user.first_name}} {{post.user.last_name}}
                            {% else %}
                                {{post.user}}
                            {% endif %}
                        </a>
                        <small class="text-info ml-3">{{post.creation_date}}</small>
                        <a href="{% url 'blog:postdetail' post.id %}" class="nav-link text-secondary">
                            {% if post.image %}

                            <img src="/media/{{post.image}}" class="card-img-top h-25" alt="...">

                            {% endif %}
                          <div class="card-body">
                            <h5 class="card-title">{{post.title}}</h5>
                            <!--<p class="card-text">{% comment %}{{post.description|linebreaksbr}}{% endcomment %}</p>-->

                          </div>
                        </a>
                    </div>

                    {% endfor %}
                {% else %}
                    <p class="h3">Sorry no posts available</p>
                {% endif %}
            </div>
            <div class="col-md-3 offset-2 text-center recent">
                <div class="row bg-light pb-4">
                    <div class="col">
                        <p class="text-uppercase text-secondary">Follow Me</p>
                        <a href="https://www.facebook.com/subhransu.das.564/" target="-_blank" class="text-muted link-muted offset-1">
                            <i class="fab fa-facebook text-secondary"></i>
                        </a>
                        <a href="https://www.instagram.com/subhransu1299/" target="_blank" class="text-muted link-muted offset-1">
                            <i class="fab fa-instagram text-secondary"></i>
                        </a>
                        <a href="https://www.linkedin.com/in/subhransu-das-908959147/" target="_blank" class="text-muted link-muted offset-1">
                            <i class="fa fa-linkedin text-secondary" aria-hidden="true"></i>
                        </a>
                        <a href="https://www.hackerrank.com/subhransud525" target="_blank" class="text-muted link-muted offset-1">
                            <i class="fab fa-hackerrank text-secondary"></i>
                        </a>
                    </div>
                </div>
                <div class="row bg-light">
                    <div class="col">
                        <p class="text-secondary text-uppercase">Category filter</p>
                        {% for post in allposts %}
                        <a href="{% url 'blog:category_posts' post %}" class="nav-link text-secondary">{{post}}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

blog/templates/blog/content.html
<section class="mt-4 content">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12 offset-md-1 posts">
                {% if posts %}
                    {% for post in posts reversed %}
                    <div class="card mb-5 w-100">
                        <a href="{% url 'blog:profile' post.user %}" class="nav-link alert text-dark mb-0">
                            {% if post.user.userprofile.profile_Image %}
                            <img src="/media/{{post.user.userprofile.profile_Image}}" id="profilepic" alt="dp" class="mr-3">
                            {% endif %}
                            {% if post.user.first_name %}
                                {{post.user.first_name}} {{post.user.last_name}}
                            {% else %}
                                {{post.user}}
                            {% endif %}
                        </a>
                        <small class="text-info ml-3">{{post.creation_date}}</small>
                        <a href="{% url 'blog:postdetail' post.id %}" class="nav-link text-secondary">
                            {% if post.image %}

                            <img src="/media/{{post.image}}" class="card-img-top h-25" alt="...">

                            {% endif %}
                          <div class="card-body">
                            <h5 class="card-title">{{post.title}}</h5>
                            <!--<p class="card-text">{% comment %}{{post.description|linebreaksbr}}{% endcomment %}</p>-->
                          </div>
                        </a>
                        <p class="text-muted h6 ml-4"><i class="fas fa-thumbs-up"></i> {{post.totalLike}} Likes</p>
                        <div class="card-footer bg-white d-flex">
                            <form action="{% url 'blog:like_post' post.id %}" method="POST">
                                {% csrf_token %}
                            <button type="submit" class="link-muted btn text-secondary ml-3">
                                        {% if request.user in post.like.all %}
                                            <i class="fas fa-thumbs-up h5 text-primary"></i>
                                            <span class="h5">Like</span>
                                        {% else %}
                                            {% comment %}okay{% endcomment %}
                                            <i class="fas fa-thumbs-up h5"></i> <span class="h5">Like</span>
                                        {% endif %}
                            </button>
                            </form>
                            <button type="button" class="link-muted btn text-secondary offset-4" data-toggle="collapse" data-target="#Comments">
                                <i class="far fa-comment-alt h5"></i> <span class="h5">Comments</span>
                            </button>
                        </div>
                        <div class="bg-light collapse" id="Comments">
                            {% if not comments.objects.all %}
                                {% for comment in comments %}
                                    {% if comment.post.id == post.id %}
                                        <strong>{{comment.name}} - {{comment.created_on}}</strong>
                                        <p>{{comment.description}}</p>
                                        <hr>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <p class="btn btn-success">Please leave a comment</p>
                            {% endif %}
                        </div>
                    </div>

                    {% endfor %}
                {% else %}
                    <p class="h3">Sorry no posts available</p>
                {% endif %}
            </div>
            <div class="col-md-3 offset-sm-2 offset-2 d-xs-none d-sm-block sticky-sidebar text-center recent">
                <div class="row bg-light pb-4">
                    <div class="col">
                        <p class="text-uppercase text-secondary">Follow Me</p>
                        <a href="https://www.facebook.com/subhransu.das.564/" target="-_blank" class="text-muted link-muted offset-1">
                            <i class="fab fa-facebook text-secondary"></i>
                        </a>
                        <a href="https://www.instagram.com/subhransu1299/" target="_blank" class="text-muted link-muted offset-1">
                            <i class="fab fa-instagram text-secondary"></i>
                        </a>
                        <a href="https://www.linkedin.com/in/subhransu-das-908959147/" target="_blank" class="text-muted link-muted offset-1">
                            <i class="fa fa-linkedin text-secondary" aria-hidden="true"></i>
                        </a>
                        <a href="https://www.hackerrank.com/subhransud525" target="_blank" class="text-muted link-muted offset-1">
                            <i class="fab fa-hackerrank text-secondary"></i>
                        </a>
                    </div>
                </div>
                <div class="row bg-light">
                    <div class="col">
                        <p class="text-secondary text-uppercase">Category filter</p>
                        {% for post in allposts %}
                        <a href="{% url 'blog:category_posts' post %}" class="nav-link text-secondary">{{post}}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

blog/templates/blog/edit_profile.html
<!-- Modal -->
<div class="modal fade" id="EditProfileModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Profile</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
            <div class="col-md-4">
                <p> Profile Picture</p>
            </div>
            <div class="mr-auto"></div>
            <div class="col-md-3">
                <ul class="nav">
                    <form action="{% url 'blog:changepropic' %}" class="dropzone" id="my-dropzone-profile">
                        {% csrf_token %}
                      <div class="fallback">
                        <input name="file" type="file" multiple class="edit_button"/>
                      </div>
                        <button type="submit" id="submit-dropzone-btn-cover" class="btn btn-primary hidden">Submit</button>
                    </form>
                </ul>
            </div>

        </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                {% if userprofile.profile_Image %}
                <img src="/media/{{userprofile.profile_Image}}" width="200px" height="200px" class="rounded-circle" alt="pro img">
                {% else %}
                <img src="/static/images/default_profile/default-profile.jpg'" width="200px" height="200px" class="rounded-circle" alt="pro img">
                {% endif %}
            </div>
        </div>

          <!-- Cover Photo  -->
          <div class="row">
            <div class="col-md-3">
                <p> Cover Picture</p>
            </div>
              <div class="mr-auto"></div>
              <div class="col-md-3">
                <ul class="nav">
                    <form action="{% url 'blog:changecoverpic' %}" class="dropzone" id="my-dropzone-cover">
                        {% csrf_token %}
                      <div class="fallback">
                        <input name="file" type="file" multiple class="edit_button"/>
                      </div>
                    </form>
                </ul>
            </div>

        </div>
        <div class="row">
            <div class="col d-flex justify-content-center">
                {% if userprofile.cover_Image %}
                <img src="/media/{{userprofile.cover_Image}}" class="w-50" alt="cover img">
                {% else %}
                    <p class="h5 border m-2 p-2">No cover image</p>
                {% endif %}
            </div>
        </div>

          <!--End of cover image-->
      </div>
    </div>
  </div>
</div>

blog/templates/blog/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
BLog
{% endblock %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}
{% block content %}
    <header class="sticky-header">
        {% include 'blog/navbar.html' %}
    </header>
    <main>
        {% include 'blog/content.html' %}
        <section class="footer">

        </section>
    </main>
{% endblock %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-md navbar-light bg-white shadow p-3">
  <div class="container-fluid">
    <a class="navbar-brand ml-4" href="{% url 'blog:home' %}"><i class="fas fa-blog"></i>log</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="mr-auto"></div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item mr-4 active">
          <a class="nav-link" href="{% url 'blog:home' %}"><i class="fas fa-home mr-2"></i>Home</a>
        </li>
        <li class="nav-item mr-4">
          <a class="nav-link" href="#"> <i class="fa fa-info-circle mr-2" aria-hidden="true"></i>About</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item mr-4">
          <a class="nav-link" href="{% url 'blog:signup' %}">SignUp</a>
        </li>
        <li class="nav-item mr-4">
          <a class="nav-link" href="{% url 'blog:login' %}"><i class="fa fa-sign-in mr-2" aria-hidden="true"></i>LogIn</a>
        </li>
        {% else %}
          <li class="nav-item mr-4">
            <a class="nav-link" href="{% url 'blog:profile' request.user.username %}"><i class="fa fa-user mr-2"></i>
              {% if request.user.first_name %}
                {{request.user.first_name|capfirst}}
              {% else %}
                {{request.user}}
              {% endif %}
            </a>
          </li>
          <li class="nav-item mr-4">
          <a class="nav-link" href="{% url 'blog:logout' %}"><i class="fa fa-sign-out mr-2" aria-hidden="true"></i>

            Logout</a>
        </li>
        {% endif %}
      </ul>

      <div class="mr-auto"></div>
    </div>
  </div>
</nav>